export const ActionTypes = {
  AUTH_USER: 'AUTH_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_CART: 'DELETE_CART',
};
