export const ActionTypes = {
  AUTH_USER: 'AUTH_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_CART: 'DELETE_CART',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  SET_TOTAL_CART_PRICE: ' SET_TOTAL_CART_PRICE',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
};
